apiVersion: v1
kind: Pod
metadata:
  name: iointensiveapptest
spec:
  containers:
  - name: iointensiveapp
    image: seveirroy/iointensiveapp
    resources:
      requests:
        cpu: 0.5
        memory: 100Mi
      limits:
        cpu: 1
        memory: 200Mi
